### PR TITLE
Refactored and renamed dateformat option

### PR DESCRIPTION
**Pull request by dsl101**
I've written this code without testing I'm afraid, as an example of what I was thinking about. In fact, it's hard for me to test on my real project, as I'm using feedparser-promised rather than your package, and so edits I make locally aren't reflected in the firebase function I use when actually running it. If at some point you were thinking about a new version, I'd support adding promises directly :).

### CODE REVIEW

**Comment by dsl101** [comment]
Hmm. Looking at the CI error, do I need to add that function to the class prototype? It doesn't depend on anything in the class, so maybe it should actually be in `../util.js`?

**Comment by dsl101** [comment]
In fact, I have a better idea for the this anyway. I want to change the option to `convertdates` and the implementation to:
```
function convertdate(date, format) {
  if (typeof date[format] === 'function') {
    return date[format]()
  } else {
    return date
  }
}
```
Let me know if you like this approach (it means _any_ date conversion can be used, and I don't think there are any extra risks), and if it should go into `util.js`.

**Comment by danmactough** [comment]
> Looking at the CI error, do I need to add that function to the class prototype?

Just use `var` instead of `const`. Dropping support for Node 4 would be a breaking change, so we can't use `let` or `const`. Soon!

**Comment by danmactough** [comment]
I like either of these approaches, with the caveat that we should create the date-converter function ONCE, when we create the feedparser with the options. So, we would probably tack `_formatDate` (or whatever you call it) onto `this` in the constructor. Make sense?

**Comment by dsl101** [comment]
@danmactough Do you get notified of updates to PR, or do I need to let you know via a comment?
Tx,

**Pull request closed without merging**
