### PR TITLE
added support for itunes iOS 11 podcast changes, including item's new…

### PR DESCRIPTION
**Pull request by avimak**
… `season`, `episode` & `episodeType` fields, and meta's (/channel's) `type` field.

### CODE REVIEW

**Comment by avimak** [comment]
@danmactough, pls let me know how can I help to push this forward.

**Comment by danmactough** [comment]
Hi, @avimak. Thanks for your PR! I'm not going to add this, however, since those itunes extensions don't map to any standard RSS properties. The point of those generic properties is to map to the RSS 2.0 spec, so I don't think it's appropriate to add them.

Note that you already have access to all that itunes-specific information (for example, in the `meta`, you can always access `meta['itunes:type']`).

**Comment by scripting** [comment]
I like this approach.

I have been able to access elements that I've added in my "source"
namespace this way.

Dave

**Comment by avimak** [comment]
@danmactough, @scripting, thanks for the comments, and I respect your point of view.

the problem with this approach, as I see it, is that you losing default values in case of missing tags, (e.g. <itunes:episodeType> defaults to 'full', <itunes:type> defaults to 'episodic', etc.).
some podcasts RSS won't have these tags (e.g. they aren't hosted on iTunes) so I thought that persisting these tags with their default values will make life much easier for clients parsing podcasts RSS.
as for standards, Apple controls most of this (podcasts) market and usually (+ historically) sets these standards, so once iOS11 is out, we should expect a mass adoption of these tags, which will probably lead to new standards. just something to keep in mind :)

**Pull request closed without merging**
